spring:
  application:
    name: resolvehub-backend
  datasource:
    url: jdbc:h2:mem:resolvehub;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    driver-class-name: org.h2.Driver
    username: resolvehub
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false

server:
  port: 8080

resolvehub:
  backend:
    service-name: resolvehub-backend
